import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': { //English
          'main_keepPressing': 'KEEP PRESSING',
          'main_player1': 'Player 1',
          'main_player2': 'Player 2',
          'main_player1win': 'won by player 1',
          'main_player2win': 'won by player 2',
          'main_start': 'START',
          'main_draw': 'draw', //draw or tie
          'popup_congratulation': 'CONGRATULATION!',
          'popup_ok': 'OK',
          'setting_language': 'Languages: ', //10
          'setting_settings': 'SETTINGS',
          'setting_theme': 'Theme: ',
          'setting_ocean': 'Ocean',
          'setting_nature': 'Nature',
          'setting_snow': 'Snow',
          'time': 'Time: ', //used in two main & setting
        },
        'id_ID': { //Indonesian
          'main_keepPressing': 'TERUS MENEKAN',
          'main_player1': 'Pemain 1',
          'main_player2': 'Pemain 2',
          'main_player1win': 'dimenangkan oleh pemain 1',
          'main_player2win': 'dimenangkan oleh pemain 2',
          'main_start': 'MULAI',
          'main_draw': 'seri',
          'popup_congratulation': 'SELAMAT!',
          'popup_ok': 'OK',
          'setting_language': 'Bahasa: ', //10
          'setting_settings': 'PENGATURAN',
          'setting_theme': 'Tema: ',
          'setting_ocean': 'Samudra',
          'setting_nature': 'Alam',
          'setting_snow': 'Salju',
          'time': 'Waktu: ',
        },
        'ms_MY': { //Malay
          'main_keepPressing': 'TERUS TEKAN',
          'main_player1': 'Pemain 1',
          'main_player2': 'Pemain 2',
          'main_player1win': 'dimenangi oleh pemain 1',
          'main_player2win': 'dimenangi oleh pemain 2',
          'main_start': 'MULAKAN',
          'main_draw': 'keputusan seri',
          'popup_congratulation': 'TAHNIAH!',
          'popup_ok': 'OK',
          'setting_language': 'Bahasa: ', //10
          'setting_settings': 'TETAPAN',
          'setting_theme': 'Tema: ',
          'setting_ocean': 'Lautan',
          'setting_nature': 'Alam',
          'setting_snow': 'Salji',
          'time': 'Masa: ',
        },
        'ja_JP': { //Japanese
          'main_keepPressing': '押し続ける',
          'main_player1': 'プレーヤー1',
          'main_player2': 'プレーヤー1',
          'main_player1win': 'プレイヤー1が勝ちました',
          'main_player2win': 'プレイヤー2が勝ちました',
          'main_start': '始める',
          'main_draw': '同点',
          'popup_congratulation': 'おめでとうございます!',
          'popup_ok': 'OK',
          'setting_language': '言語: ', //10
          'setting_settings': '設定',
          'setting_theme': 'テーマ: ',
          'setting_ocean': '海洋',
          'setting_nature': '自然',
          'setting_snow': '雪',
          'time': '時間: '
        },
        'zh_CN': { // Chinese (Simplified)
          'main_keepPressing': '继续按',
          'main_player1': '选手一',
          'main_player2': '选手二',
          'main_player1win': '玩家 1 获胜',
          'main_player2win': '玩家 2 获胜',
          'main_start': '开始',
          'main_draw': '平局',
          'popup_congratulation': '祝贺!',
          'popup_ok': 'OK',
          'setting_language': '语言: ', //10
          'setting_settings': '设置',
          'setting_theme': '主题: ',
          'setting_ocean': '海洋',
          'setting_nature': '自然',
          'setting_snow': '雪',
          'time': '时间: ',
        },
        'hi_IN': { //Hindi
          'main_keepPressing': 'दबाते रहो',
          'main_player1': 'खिलाड़ी 1',
          'main_player2': 'खिलाड़ी 2',
          'main_player1win': 'खिलाड़ी 1 . द्वारा जीता',
          'main_player2win': 'खिलाड़ी 2 . द्वारा जीता',
          'main_start': 'शुरु',
          'main_draw': 'टाई',
          'popup_congratulation': 'बधाई!',
          'popup_ok': 'OK',
          'setting_language': 'बोली: ', //10
          'setting_settings': 'समायोजन',
          'setting_theme': 'विषय: ',
          'setting_ocean': 'महासागर',
          'setting_nature': 'प्रकृति',
          'setting_snow': 'बर्फ',
          'time': 'समय: ',
        },
        'ko_KR': { //Korean
          'main_keepPressing': '계속 눌러',
          'main_player1': '플레이어 1',
          'main_player2': '플레이어 2',
          'main_player1win': '플레이어 1이 이겼습니다.',
          'main_player2win': '플레이어 2이 이겼습니다.',
          'main_start': '시작',
          'main_draw': '동점',
          'popup_congratulation': '축하!',
          'popup_ok': 'OK',
          'setting_language': '언어: ', //10
          'setting_settings': '설정',
          'setting_theme': '주제: ',
          'setting_ocean': '대양',
          'setting_nature': '자연',
          'setting_snow': '눈',
          'time': '시각: ',
        },
        'ru_RU': { //Russian
          'main_keepPressing': 'ПРОДОЛЖАЙТЕ НАЖАТЬ',
          'main_player1': 'первый игрок',
          'main_player2': 'второй игрок',
          'main_player1win': 'выиграл игрок 1',
          'main_player2win': 'выиграл игрок 2',
          'main_start': 'НАЧАЛО',
          'main_draw': 'игра вничью',
          'popup_congratulation': 'ПОЗДРАВЛЯЕМ!',
          'popup_ok': 'OK',
          'setting_language': 'Языки: ', //10
          'setting_settings': 'НАСТРОЙКИ',
          'setting_theme': 'Тема: ',
          'setting_ocean': 'Океан',
          'setting_nature': 'Природа',
          'setting_snow': 'Снег',
          'time': 'Время: ',
        },
        'pt_PT': { //Portuguese
          'main_keepPressing': 'CONTINUE PRESSIONANDO',
          'main_player1': 'Jogador 1',
          'main_player2': 'Jogador 2',
          'main_player1win': 'ganhou pelo jogador 1',
          'main_player2win': 'ganhou pelo jogador 2',
          'main_start': 'COMEÇAR',
          'main_draw': 'empate',
          'popup_congratulation': 'PARABÉNS!',
          'popup_ok': 'OK',
          'setting_language': 'línguas: ', //10
          'setting_settings': 'DEFINIÇÕES',
          'setting_theme': 'Tema: ',
          'setting_ocean': 'oceano',
          'setting_nature': 'Natureza',
          'setting_snow': 'Neve',
          'time': 'Tempo: ',
        }
      };
}
